name: Publish to github pages

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js
      uses: actions/setup-node@v1
      with:
        node-version: '14.x'
    - run: npm config --local user.name Giles Dring
    - run: npm config --local user.email giles.dring@odileeds.org
    - run: npm ci
    - run: npm run deploy
